# nnictl create --config config.yaml --port 8081
search_space:
  weight_decay:
    _type: choice
    # _value: [ 0.1, 0.01, 0.001, 0.0001, 0.00001, 0 ]
    _value:  [0.1, 0.01, 0.001, 0.0001]
  lr:
    _type: choice
    # _value: [ 0.01 ]
    _value: [0.1, 0.01, 0.001, 0.0001]
  ssm_temp:
    _type: choice
    # _value: [ 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.9, 0.1 ]
    _value: [0.05, 0.10, 0.15, 0.20, 0.25, 0.30]

trial_command: python main.py --model=mf --dataset='amazon-beauty_5' --lr 0.01 --weight_decay 0 --ssm_temp 0.1 --trainbatch 1024 --num_negative_items 1024 --cuda 0 --loss psl --epochs 50
trial_code_directory: ..

trialGpuNumber: 1

trial_concurrency: 2
max_trial_number: 50

tuner:
  name: TPE
  class_args:
    optimize_mode: maximize

training_service:
  platform: local
  maxTrialNumberPerGpu: 1
  useActiveGpu: true
  gpuIndices: [6,7]
